{{- if .Values.kubernetes.enableClusterAccountMode }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rna-{{ .Release.Name }}-cr
rules:
{{ .Values.kubernetes.clusterRoleRules | toYaml }}
{{- end }}