{{- if .Values.kubernetes.enableClusterAccountMode }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rna-{{ .Release.Name }}-cr-binding
  labels:
    {{- include "armory-remote-network-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: remote-network-agent-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rna-{{ .Release.Name }}-cr
{{- end }}