{{- if .Values.kubernetes.enableClusterAccountMode }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: remote-network-agent-service-account
  labels:
    {{- include "armory-remote-network-agent.labels" . | nindent 4 }}
  {{- with .Values.kubernetes.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}