name: Publish Chart

on:
  release:
    types: [released]

jobs:
  publish-chart:
    name: Publish Chart
    runs-on: ubuntu-latest
    env:
      ARMORY_JFROG_CHARTS_URL: https://armory.jfrog.io/artifactory/charts
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Get version
        id: get-version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
      - name: Package and Publish Remote Network Agent Helm Package
        run: |
          set -eu
          echo "Publising agent helm chart..."
          sed 's/0.0.0-iam-am-changed-in-ci/${{ steps.get-version.outputs.version}}/' Chart.yaml > ChartTemp.yaml
          mv ChartTemp.yaml Chart.yaml
          [ -d helm ] || mkdir helm
          cd helm
          helm package ../
          curl -f -u ${{secrets.ARTIFACTORY_USER}}:${{secrets.ARTIFACTORY_TOKEN}} -o "index.yaml" "${{env.ARMORY_JFROG_CHARTS_URL}}/index.yaml"
          helm repo index --merge index.yaml --url "${{env.ARMORY_JFROG_CHARTS_URL}}" .
          for f in *; do
            curl -f -u ${{secrets.ARTIFACTORY_USER}}:${{secrets.ARTIFACTORY_TOKEN}} -X PUT "${{env.ARMORY_JFROG_CHARTS_URL}}/${f}" -T "${PWD}/${f}"
          done