###
#
# On pull_request creation/updates run the checks and submit to sonar qube
#
###
name: Pull Request Analysis

on: [ pull_request ]

jobs:
  pull-request-analysis:
    name: Pull Request Analysis
    runs-on: ubuntu-latest
    steps:
      - name: run helm chart unit tests
        uses: docker://quintush/helm-unittest:3.7.1-0.2.8
        with:
          args: --helm3 .