###
#
# On pull_request creation/updates run the checks and submit to sonar qube
#
###
name: Pull Request Analysis

on: [ pull_request ]

jobs:
  pull-request-analysis:
    name: Pull Request Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run helm chart unit tests
        run: make check
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: 'reports/test/*'