###
#
# On pull_request creation/updates run the checks and submit to sonar qube
#
###
name: Pull Request Analysis

on: [ pull_request ]

jobs:
  pull-request-analysis:
    name: Pull Request Analysis
    runs-on: ubuntu-latest
    steps:
      - name: run helm chart unit tests
        run: |
          helm plugin install https://github.com/quintush/helm-unittest
          helm unittest --helm3 .
          helm package .