###
#
# On pull_request creation/updates run the checks and submit to sonar qube
#
###
name: Pull Request Analysis

on: [ pull_request ]

jobs:
  pra:
    name: Pull Request Analysis
    runs-on: ubuntu-latest
    container:
      image: quintush/helm-unittest:3.7.1-0.2.8
    steps:
      - name: run helm chart unit tests
        run: |
          helm unittest --helm3 .
          helm package .