###
#
# On pull_request creation/updates run the checks and submit to sonar qube
#
###
name: Pull Request Analysis

on: [ pull_request ]

jobs:
  pull-request-analysis:
    name: Pull Request Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: run helm chart unit tests
        run: make check
      - name: Upload Tests Reports to Github
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports/test/*